# -*- coding: utf-8 -*-
"""webassembly_site_demo_poc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xJ1Ry0lgugxoezPKKZJ8jnp-DwdEGAA
"""

!pip install --quiet flask
!pip install --quiet pyngrok

# Optional: For enhanced server capabilities
!pip install --quiet waitress

# Using inline event handlers for Colab compatibility
from IPython.display import HTML, display

html_content = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WebAssembly Dynamic Website</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        header {
            background: rgba(255, 255, 255, 0.95);
            padding: 1rem 0;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            border-radius: 10px;
            margin-bottom: 30px;
        }
        nav {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 2rem;
        }
        .logo {
            font-size: 1.8rem;
            font-weight: bold;
            color: #764ba2;
        }
        .dropdown {
            position: relative;
            display: inline-block;
        }
        .dropdown-btn {
            background: #764ba2;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: all 0.3s ease;
        }
        .dropdown-btn:hover {
            background: #5a3a7a;
            transform: translateY(-2px);
        }
        .dropdown-content {
            display: none;
            position: absolute;
            background: white;
            min-width: 200px;
            box-shadow: 0 8px 16px rgba(0,0,0,0.1);
            z-index: 1000;
            border-radius: 5px;
            overflow: hidden;
            top: 100%;
            right: 0;
        }
        .dropdown-content a {
            color: #333;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            transition: background 0.3s ease;
            cursor: pointer;
        }
        .dropdown-content a:hover {
            background: #f1f1f1;
        }
        .dropdown.show .dropdown-content {
            display: block;
        }
        .content {
            background: rgba(255, 255, 255, 0.95);
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            min-height: 500px;
        }
        .page {
            display: none;
            animation: fadeIn 0.5s ease-in;
        }
        .page.active {
            display: block;
        }
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .hero {
            text-align: center;
            padding: 60px 0;
        }
        .hero h1 {
            font-size: 3rem;
            margin-bottom: 20px;
            color: #764ba2;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
        }
        .hero p {
            font-size: 1.2rem;
            margin-bottom: 30px;
            color: #666;
        }
        .feature-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 30px;
            margin-top: 40px;
        }
        .feature-card {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 30px;
            border-radius: 10px;
            text-align: center;
            transition: transform 0.3s ease;
        }
        .feature-card:hover {
            transform: translateY(-5px);
        }
        .feature-card h3 {
            color: #764ba2;
            margin-bottom: 15px;
        }
        #wasm-output {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #764ba2;
            margin-top: 20px;
            font-family: monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <nav>
                <div class="logo">WebAssembly Demo</div>
                <div class="dropdown" id="navDropdown">
                    <button class="dropdown-btn" onclick="toggleDropdown()">Navigate ▼</button>
                    <div class="dropdown-content">
                        <a href="javascript:void(0)" onclick="showPage('home')">Home</a>
                        <a href="javascript:void(0)" onclick="showPage('about')">About</a>
                        <a href="javascript:void(0)" onclick="showPage('services')">Services</a>
                        <a href="javascript:void(0)" onclick="showPage('contact')">Contact</a>
                        <a href="javascript:void(0)" onclick="showPage('wasm-demo')">WebAssembly Demo</a>
                    </div>
                </div>
            </nav>
        </header>
        <main class="content">
            <div id="home" class="page active">
                <div class="hero">
                    <h1>Welcome to WebAssembly Demo</h1>
                    <p>Experience the power of WebAssembly in your browser</p>
                </div>
                <div class="feature-grid">
                    <div class="feature-card">
                        <h3>High Performance</h3>
                        <p>WebAssembly provides near-native performance for web applications</p>
                    </div>
                    <div class="feature-card">
                        <h3>Language Agnostic</h3>
                        <p>Compile code from C, C++, Rust, and other languages to WebAssembly</p>
                    </div>
                    <div class="feature-card">
                        <h3>Secure</h3>
                        <p>Runs in a sandboxed environment with strong security guarantees</p>
                    </div>
                </div>
            </div>
            <div id="about" class="page">
                <h2>About This Project</h2>
                <p>This website demonstrates the integration of WebAssembly with modern web technologies. WebAssembly (WASM) is a binary instruction format that enables high-performance applications on web pages.</p>
                <br>
                <p>Key benefits include:</p>
                <ul style="margin: 20px 0; padding-left: 30px;">
                    <li>Near-native performance</li>
                    <li>Compact binary format</li>
                    <li>Memory-safe execution</li>
                    <li>Cross-platform compatibility</li>
                </ul>
            </div>
            <div id="services" class="page">
                <h2>Our Services</h2>
                <div class="feature-grid">
                    <div class="feature-card">
                        <h3>WebAssembly Development</h3>
                        <p>Custom WebAssembly modules for high-performance web applications</p>
                    </div>
                    <div class="feature-card">
                        <h3>Performance Optimization</h3>
                        <p>Optimize your existing applications with WebAssembly integration</p>
                    </div>
                    <div class="feature-card">
                        <h3>Cross-Platform Solutions</h3>
                        <p>Deploy the same codebase across web, desktop, and mobile platforms</p>
                    </div>
                </div>
            </div>
            <div id="contact" class="page">
                <h2>Contact Us</h2>
                <div style="max-width: 600px; margin: 0 auto;">
                    <p>Get in touch with our WebAssembly experts:</p>
                    <br>
                    <div style="background: #f8f9fa; padding: 30px; border-radius: 10px;">
                        <p><strong>Email:</strong> info@wasmdemp.com</p>
                        <p><strong>Phone:</strong> +1 (555) 123-4567</p>
                        <p><strong>Address:</strong> 123 Web Street, Browser City, Internet 12345</p>
                    </div>
                </div>
            </div>
            <div id="wasm-demo" class="page">
                <h2>WebAssembly Demo</h2>
                <p>This page demonstrates WebAssembly functionality. Click the button below to see mathematical calculations.</p>
                <div style="margin: 30px 0;">
                    <button onclick="runWasmDemo()" style="background: #764ba2; color: white; padding: 12px 24px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">
                        Run WebAssembly Calculation
                    </button>
                </div>
                <div id="wasm-output">
                    Click the button above to run WebAssembly calculations...
                </div>
            </div>
        </main>
    </div>

    <script>
        // Debug function to check if JavaScript is working
        console.log('JavaScript loaded successfully');

        // Global variables
        var wasmModule = null;

        // WebAssembly bytecode
        var wasmCode = new Uint8Array([
            0x00, 0x61, 0x73, 0x6d,
            0x01, 0x00, 0x00, 0x00,
            0x01, 0x07, 0x01, 0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f,
            0x03, 0x02, 0x01, 0x00,
            0x07, 0x07, 0x01, 0x03, 0x61, 0x64, 0x64, 0x00, 0x00,
            0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b
        ]);

        // Toggle dropdown function
        function toggleDropdown() {
            console.log('Toggle dropdown clicked');
            var dropdown = document.getElementById("navDropdown");
            if (dropdown.classList.contains("show")) {
                dropdown.classList.remove("show");
            } else {
                dropdown.classList.add("show");
            }
        }

        // Show page function
        function showPage(pageId) {
            console.log('Showing page: ' + pageId);

            // Hide all pages
            var pages = document.getElementsByClassName('page');
            for (var i = 0; i < pages.length; i++) {
                pages[i].classList.remove('active');
            }

            // Show selected page
            var targetPage = document.getElementById(pageId);
            if (targetPage) {
                targetPage.classList.add('active');
                console.log('Page switched to: ' + pageId);
            } else {
                console.error('Page not found: ' + pageId);
            }

            // Close dropdown
            var dropdown = document.getElementById("navDropdown");
            dropdown.classList.remove('show');
        }

        // Initialize WebAssembly
        function initWasm() {
            return WebAssembly.instantiate(wasmCode)
                .then(function(result) {
                    wasmModule = result;
                    console.log('WebAssembly module loaded');
                    return true;
                })
                .catch(function(error) {
                    console.error('WebAssembly failed:', error);
                    return false;
                });
        }

        // Run WebAssembly demo
        function runWasmDemo() {
            console.log('WASM demo clicked');
            var output = document.getElementById('wasm-output');

            if (!wasmModule) {
                output.innerHTML = '<h3>Initializing WebAssembly...</h3><p>Loading module...</p>';
                initWasm().then(function(success) {
                    if (success) {
                        setTimeout(function() { runWasmDemo(); }, 500);
                    } else {
                        runJSDemo();
                    }
                });
                return;
            }

            try {
                var num1 = Math.floor(Math.random() * 1000);
                var num2 = Math.floor(Math.random() * 1000);
                var wasmResult = wasmModule.instance.exports.add(num1, num2);
                var jsResult = num1 + num2;

                // Performance test
                var iterations = 50000;

                var wasmStart = performance.now();
                for (var i = 0; i < iterations; i++) {
                    wasmModule.instance.exports.add(i, i + 1);
                }
                var wasmTime = performance.now() - wasmStart;

                var jsStart = performance.now();
                for (var i = 0; i < iterations; i++) {
                    i + (i + 1);
                }
                var jsTime = performance.now() - jsStart;

                output.innerHTML =
                    '<h3>WebAssembly Results</h3>' +
                    '<p><strong>Calculation:</strong> ' + num1 + ' + ' + num2 + ' = ' + wasmResult + '</p>' +
                    '<p><strong>JavaScript Result:</strong> ' + jsResult + '</p>' +
                    '<p><strong>Match:</strong> ' + (wasmResult === jsResult ? '✅ Yes' : '❌ No') + '</p>' +
                    '<h4>Performance (' + iterations.toLocaleString() + ' ops)</h4>' +
                    '<p><strong>WASM:</strong> ' + wasmTime.toFixed(2) + 'ms</p>' +
                    '<p><strong>JS:</strong> ' + jsTime.toFixed(2) + 'ms</p>' +
                    '<p><strong>Ratio:</strong> ' + (jsTime / wasmTime).toFixed(2) + 'x faster</p>';

            } catch (error) {
                console.error('WASM error:', error);
                runJSDemo();
            }
        }

        // JavaScript fallback
        function runJSDemo() {
            var output = document.getElementById('wasm-output');
            var num1 = Math.floor(Math.random() * 1000);
            var num2 = Math.floor(Math.random() * 1000);
            var result = num1 + num2;

            output.innerHTML =
                '<h3>JavaScript Demo</h3>' +
                '<p><strong>Calculation:</strong> ' + num1 + ' + ' + num2 + ' = ' + result + '</p>' +
                '<p>WebAssembly not available, using JavaScript.</p>';
        }

        // Close dropdown when clicking outside
        document.onclick = function(event) {
            if (!event.target.matches('.dropdown-btn')) {
                var dropdown = document.getElementById("navDropdown");
                if (dropdown && dropdown.classList.contains('show')) {
                    dropdown.classList.remove('show');
                }
            }
        }

        // Initialize when page loads
        setTimeout(function() {
            console.log('Initializing WebAssembly...');
            initWasm();
        }, 500);

        console.log('All functions defined successfully');
    </script>
</body>
</html>'''

# Display the website
display(HTML(html_content))
print("Website loaded with simplified JavaScript")
print("Using inline event handlers for better Colab compatibility")
print("Try clicking the dropdown menu now")
print("All functions should work properly")

